[target.aarch64-unknown-linux-gnu]
pre-build = [
    "apt-get update && apt-get install -y curl unzip",
    "curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v28.3/protoc-28.3-linux-x86_64.zip",
    "unzip -o protoc-28.3-linux-x86_64.zip -d /usr/local",
    "chmod 755 /usr/local/bin/protoc",
    "rm protoc-28.3-linux-x86_64.zip",
]
